/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LobbyScreen;

import Logic.Constantes;
import GUI.GameWindow;
import Logic.cliente;

/**
 *
 * @author ellioth
 */
public class Lobby extends javax.swing.JFrame implements Constantes{
    
    private cliente _cliente;
    private GameWindow _GameWPlayer;
    
    /**
     * Creates new form Lobby
     */
    public Lobby() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IpField = new javax.swing.JTextField();
        PortField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ConnBtt = new javax.swing.JButton();
        PlayerBtt = new javax.swing.JButton();
        ExptectorBtt1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crazy Break Out");
        setBackground(new java.awt.Color(254, 254, 254));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(450, 400));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Crazy Break Out");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 30, 120, 30);

        IpField.setToolTipText("ingrese el IP");
        getContentPane().add(IpField);
        IpField.setBounds(100, 170, 160, 40);

        PortField.setToolTipText("ingrese el puerto");
        getContentPane().add(PortField);
        PortField.setBounds(100, 110, 160, 40);

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Puerto:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 120, 60, 21);

        jLabel3.setBackground(new java.awt.Color(1, 1, 1));
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("IP:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 170, 17, 21);

        ConnBtt.setText("Conectar");
        ConnBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnBttActionPerformed(evt);
            }
        });
        getContentPane().add(ConnBtt);
        ConnBtt.setBounds(300, 150, 120, 33);

        PlayerBtt.setText("Jugador");
        PlayerBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerBttActionPerformed(evt);
            }
        });
        getContentPane().add(PlayerBtt);
        PlayerBtt.setBounds(270, 270, 130, 30);

        ExptectorBtt1.setText("Espectador");
        ExptectorBtt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExptectorBtt1ActionPerformed(evt);
            }
        });
        getContentPane().add(ExptectorBtt1);
        ExptectorBtt1.setBounds(70, 269, 130, 30);

        jPanel6.setBackground(new java.awt.Color(255, 0, 16));
        getContentPane().add(jPanel6);
        jPanel6.setBounds(230, 100, 120, 100);

        jPanel5.setBackground(new java.awt.Color(0, 97, 255));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(120, 100, 120, 100);

        jPanel8.setBackground(new java.awt.Color(72, 225, 34));
        getContentPane().add(jPanel8);
        jPanel8.setBounds(0, 100, 120, 100);

        jPanel7.setBackground(new java.awt.Color(255, 76, 0));
        getContentPane().add(jPanel7);
        jPanel7.setBounds(350, 100, 120, 100);

        jPanel4.setBackground(new java.awt.Color(0, 97, 255));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 120, 100);

        jPanel3.setBackground(new java.awt.Color(255, 76, 0));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(230, 0, 120, 100);

        jPanel2.setBackground(new java.awt.Color(255, 0, 16));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(110, 0, 120, 100);

        jPanel1.setBackground(new java.awt.Color(72, 225, 34));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(350, 0, 120, 100);

        jPanel9.setBackground(new java.awt.Color(3, 134, 251));
        getContentPane().add(jPanel9);
        jPanel9.setBounds(180, 310, 110, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * metodo para enviarle una alerta a la pantalla principal de que somos
     * un jugador y vamos a empezar a mandarle mensajes
     * @param evt 
     */
    private void PlayerBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerBttActionPerformed
        // TODO add your handling code here:
        _GameWPlayer.setFalgForPlayer(true);
        _GameWPlayer.createScreen();
        (new Thread(_GameWPlayer)).start();
        _GameWPlayer.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_PlayerBttActionPerformed

    private void ConnBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnBttActionPerformed
        // TODO add your handling code here:
        if(!PortField.getText().equals("") && !IpField.getText().equals("")){
            _cliente=new cliente(Integer.parseInt(PortField.getText()), IpField.getText());
            _cliente.alertServerViewer();
            (new Thread(_cliente)).start();
            _GameWPlayer= new GameWindow(_cliente);
            System.out.println("Conexion con exito, esperando para empezar...");
            //_GameWPlayer.setVisible(true);
        }
        else
            System.out.println("Error:faltan datos para la conexión");
    }//GEN-LAST:event_ConnBttActionPerformed
    
    /**
     * metodo para enviarle una alerta a la pantalla principal de que somos
     * un expectador y vamos a visualizar el juego nada mas 
     * @param evt 
     */
    private void ExptectorBtt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExptectorBtt1ActionPerformed
        // TODO add your handling code here:
        _GameWPlayer.setFalgForPlayer(false);
        _GameWPlayer.createScreen();
        (new Thread(_GameWPlayer)).start();
        _GameWPlayer.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ExptectorBtt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConnBtt;
    private javax.swing.JButton ExptectorBtt1;
    private javax.swing.JTextField IpField;
    private javax.swing.JButton PlayerBtt;
    private javax.swing.JTextField PortField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
