/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LobbyScreen;

import GUI.GameWindow;
import java.awt.Color;
import prueba_cliente_sender.cliente;

/**
 *
 * @author ellioth
 */
public class Lobby extends javax.swing.JFrame {
    
    private cliente _cliente;
    private GameWindow _GameWPlayer;
    /**
     * Creates new form Lobby
     */
    public Lobby() {
        this.getContentPane().setBackground(Color.RED);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IpField = new javax.swing.JTextField();
        PortField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ConnBtt = new javax.swing.JButton();
        ExptectorBtt = new javax.swing.JButton();
        PlayrBtt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crazy Break Out");
        setBackground(new java.awt.Color(255, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(450, 364));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Crazy Break Out");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 30, 120, 30);

        IpField.setToolTipText("ingrese el IP");
        getContentPane().add(IpField);
        IpField.setBounds(100, 170, 160, 40);

        PortField.setToolTipText("ingrese el puerto");
        getContentPane().add(PortField);
        PortField.setBounds(100, 110, 160, 40);

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Puerto:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 120, 60, 17);

        jLabel3.setBackground(new java.awt.Color(1, 1, 1));
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("IP:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 170, 16, 17);

        ConnBtt.setText("Conectar");
        ConnBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnBttActionPerformed(evt);
            }
        });
        getContentPane().add(ConnBtt);
        ConnBtt.setBounds(300, 150, 120, 29);

        ExptectorBtt.setText("Espectador");
        ExptectorBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExptectorBttActionPerformed(evt);
            }
        });
        getContentPane().add(ExptectorBtt);
        ExptectorBtt.setBounds(70, 269, 130, 30);

        PlayrBtt.setBackground(new java.awt.Color(1, 1, 1));
        PlayrBtt.setText("Jugador");
        PlayrBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayrBttActionPerformed(evt);
            }
        });
        getContentPane().add(PlayrBtt);
        PlayrBtt.setBounds(270, 270, 130, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExptectorBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExptectorBttActionPerformed
        // TODO add your handling code here:
        _GameWPlayer= new GameWindow(_cliente, false);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ExptectorBttActionPerformed

    private void PlayrBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayrBttActionPerformed
        // TODO add your handling code here:
        _GameWPlayer= new GameWindow(_cliente, true);
        this.setVisible(false);
        this.dispose();
        (new Thread(_GameWPlayer)).start();
        
    }//GEN-LAST:event_PlayrBttActionPerformed

    private void ConnBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnBttActionPerformed
        // TODO add your handling code here:
        _cliente=new cliente(Integer.parseInt(PortField.getText()), IpField.getText());
    }//GEN-LAST:event_ConnBttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConnBtt;
    private javax.swing.JButton ExptectorBtt;
    private javax.swing.JTextField IpField;
    private javax.swing.JButton PlayrBtt;
    private javax.swing.JTextField PortField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
